### PR TITLE
Allows indexes containing hyphens

### PR DESCRIPTION
**Pull request by josephzidell**
Fixes this code:
```js
foo['bar-baz']
```

### CODE REVIEW

**Comment by jrfnl** [comment]
@josephzidell Could you please add a unit test for your change ?

**Comment by josephzidell** [comment]
@jrfnl Is that what you had in mind?

**Comment by jrfnl** [comment]
> @jrfnl Is that what you had in mind?

@josephzidell Sort of, though I see no reason why all the other lines in the test file were changed.
The new test could have just been added at the end of the test case file. That way, the diff is cleaner and it's a lot clearer what your actual change was.

**Comment by josephzidell** [comment]
Updated

**Comment by gsherwood** [comment]
Missed this one - but closing now as the JS tokenizer will be removed in version 4, so no work is being done to improve it. Sorry this was missed when you submitted it.

**Pull request closed without merging**
