### PR TITLE
Report correct problem when another tag appears before param tag

### PR DESCRIPTION
**Pull request by phil-davis**
Fixes issue #1905 

A tag group that contains a ``param`` tag could have other tags either before or after it in the group. When we see the first ``param`` tag, there might have already been some non-param tags already processed in the group. 

The existing code, when it came across a ``param`` tag and it was already in "the middle" of processing a tag group that was not a ``param`` group, would complain about ``Parameter tags must be grouped together in a doc comment`` - that was not correct. Actually it can just decide that it has now come across the ``param`` group.

Then the processing to report about ``Tag cannot be grouped with parameter tags in a doc comment`` needs to be done later, during another pass through the tag groups. Then that can detect other tags in a ``param`` tag group occurring either before or after the ``param`` tag(s).

### CODE REVIEW

**Comment by gsherwood** [comment]
See discussion on #1905

**Comment by gsherwood** [comment]
I tried this change with this sample file:
```php
<?php
/**
 * Some text about this step/method
 *
 * @see    Bar
 * @param  string $name
 * @see    Foo
 * @param  string $folder
 * @return void
 */
```
Previously, you'd get these errors (I'm only focusing on the param grouping ones):
```
  6 | ERROR   | [ ] Parameter tags must be grouped together in a doc comment (Generic.Commenting.DocComment.ParamGroup)
  7 | ERROR   | [ ] Tag cannot be grouped with parameter tags in a doc comment (Generic.Commenting.DocComment.NonParamGroup)
  7 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
  8 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
  9 | ERROR   | [ ] Tag cannot be grouped with parameter tags in a doc comment (Generic.Commenting.DocComment.NonParamGroup)
```
With this change, I now get:
```
  5 | ERROR   | [ ] Tag cannot be grouped with parameter tags in a doc comment (Generic.Commenting.DocComment.NonParamGroup)
  7 | ERROR   | [ ] Tag cannot be grouped with parameter tags in a doc comment (Generic.Commenting.DocComment.NonParamGroup)
  7 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
  8 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
  9 | ERROR   | [ ] Tag cannot be grouped with parameter tags in a doc comment (Generic.Commenting.DocComment.NonParamGroup)
````
So you end up losing the `Parameter tags must be grouped together in a doc comment` error message, which is the one I know you want to keep here. You do retain the `Tags must be grouped together in a doc comment` error for the second `@param` tag, but I'm wondering if losing that first error message is the desired outcome of this change.

**Comment by phil-davis** [comment]
That looks good to me. In my mind, ``Parameter tags must be grouped together in a doc comment`` is about seeing all the ``param`` tags in a single block of tags (in whatever mess of an order like your example. Then withing the block that has the ``param`` tags, there can be the other problems:

``Tags must be grouped together in a doc comment`` - which applies equally well to the ``param`` tag or to other tags, like ``see`` in your example. Each tag name (``see``, ``param``, ``return`` in the example) must be be grouped together.

``Tag cannot be grouped with parameter tags in a doc comment`` - which applies to all the non-``param`` tags that appear wherever in a block of tags that contains any ``param`` tag.

So I can suppress ``Tag cannot be grouped with parameter tags in a doc comment`` and get:

```
  7 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
  8 | ERROR   | [ ] Tags must be grouped together in a doc comment (Generic.Commenting.DocComment.TagsNotGrouped)
```

and then I can sort the tags out "properly":
```
<?php
/**
 * Some text about this step/method
 *
 * @see    Bar
 * @see    Foo
 * @param  string $name
 * @param  string $folder
 * @return void
 */
```
and (for me) this doc-block will now pass.

**Comment by phil-davis** [comment]
I added a test case also.

**Comment by gsherwood** [comment]
Thanks for the feedback and test case. This change will be in the 3.3.0 release.

**Pull request merged**
