### PR TITLE
[3.0] Added missing lowercase keywords

### PR DESCRIPTION
**Pull request by webimpress**
- function (closure)
  - parent
  - self
  - yield
  - yield from

### CODE REVIEW

**Comment by jrfnl** [comment]
Partial duplicate of #1458 ?

**Comment by jrfnl** [comment]
After the update of https://github.com/squizlabs/PHP_CodeSniffer/pull/1524, should `T_YIELD_FROM` be added here as well ?

**Comment by webimpress** [comment]
@jrfnl Updated :-) Of course #1524 must be merged first.

**Comment by webimpress** [comment]
Rebased, now all tests pass.

**Comment by gsherwood** [comment]
Thanks for the PR and the tests.

**Pull request merged**
