### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by gmponos**
Not sure but I think this the branch alias should be dev-3.x

### CODE REVIEW

**Comment by gsherwood** [comment]
You're not sure. I'm not sure. Nobody has complained. Probably best not to change anything.

**Comment by gmponos** [comment]
What I mostly meant is that I haven't tested it. I thought that you might have some more experience in composer.

I will test it and let you know.

**Comment by gsherwood** [comment]
> I thought that you might have some more experience in composer.

Unfortunately, I have none. The composer.json changes are typically provided by other people, so I have no idea if there is a problem. But nobody has reported one.

Given that 3.0 will be merged into master pretty soon, it may not matter anyway.

**Comment by gmponos** [comment]
> Given that 3.0 will be merged into master pretty soon, it may not matter anyway.

if that's the case then you are correct. It wont matter.

**Pull request closed without merging**
