### PR TITLE
move Config::$settings description to class annotations

### LINKED ISSUE #2861: Make properties on Config class less magic
Currently Config class has properties accessed via `__get()`.

Other  tools like phpstan/psalm yell at me that I can't get undefined property (to quote phpstan output `Access to an undefined property PHP_CodeSniffer\Config::$basepath`).

My idea is to annotate every magic property that available on the Config class with `@property` annotation. And also move the description of `$this->settings` to them.

I'm talking about this part of code
https://github.com/squizlabs/PHP_CodeSniffer/blob/dceec07328401de6211037abbb18bda423677e26/src/Config.php#L100

### PR DESCRIPTION
**Pull request by vladyslavstartsev**
close #2861

I've moved description from property comment to class level annotaion

### CODE REVIEW

**Comment by jrfnl** [comment]
Just a note: something weird is going on as Travis isn't building this PR, even though their status page says all systems are operational.

**Comment by vladyslavstartsev** [comment]
Anything that I can do with this issue?

@jrfnl

**Comment by jrfnl** [comment]
@vladyslavstartsev You may want to try to force-push the branch again to see if that gets the Travis build running. May just have been a hickup in the system.

**Comment by vladyslavstartsev** [comment]
I've managed to be unflagged by Travis team

If this happens again here, here is the link https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191

**Comment by jrfnl** [comment]
> I've managed to be unflagged by Travis team
> 

@vladyslavstartsev Glad to hear it ;-)

**Comment by gsherwood** [comment]
Thanks for doing this.

**Pull request merged**
