### PR TITLE
Added missing scope_* values with T_START_NOWDOC token

### LINKED ISSUE #1531: Missing scope_* values with T_START_NOWDOC token
With `T_START_HEREDOC` token we have following values:
```
scope_condition = ...
scope_opener = ...
scope_closer = ...
```

I would expect to have the same also with `T_START_NOWDOC` token.

### PR DESCRIPTION
**Pull request by webimpress**
Resolves #1531

### CODE REVIEW

**Comment by webimpress** [comment]
@gsherwood Can we have this hotfix in 3.0.2, please?

**Comment by gsherwood** [comment]
> Can we have this hotfix in 3.0.2, please?

I was going to attempt to release today (assuming I find time), but I'll try.

**Comment by gsherwood** [comment]
Merging this resulted in a fatal error when printing debug output due to the use of `token_name()` on a PHPCS-supplied token (`T_START_NOWDOC`). I have replaced the calls to a new Util method that supports both built-in and PHPCS-supplied tokens.

**Comment by webimpress** [comment]
@gsherwood travis build didn't show any issues. You said the fatal error was on debug mode. Maybe then we should update somehow travis configuration to check also debug mode?

Should we use now everywhere new method from `Util` instead of `token_name()` ?

**Comment by gsherwood** [comment]
> Should we use now everywhere new method from Util instead of token_name() ?

I made the change everywhere it was needed in my commit, so it should all be fine now.

**Pull request merged**
