### PR TITLE
Update ObjectOperatorSpacingSniff.php

### PR DESCRIPTION
**Pull request by bondas83**
Validate and Class :: staticFunction() and fix to Class::staticFunction() without spaces

### CODE REVIEW

**Comment by jrfnl** [comment]
@bondas83 You may want to add some unit tests for the change ?

**Comment by bondas83** [comment]
I add unit tests with new pullrequest #1543

**Comment by webimpress** [comment]
@bondas83 why you've added tests in separate PR not here?

**Comment by bondas83** [comment]
i only week in github, and first PR i do from web, second from PC. And dont know ho to fix

**Comment by bondas83** [comment]
i fix PR

**Comment by gsherwood** [comment]
Thanks for this change.

**Pull request merged**
