### PR TITLE
Lint with display_errors enabled

### PR DESCRIPTION
**Pull request by raul338**
Cloned and noticed that the testsuite failed on my pc, since I have display_error disabled.

This PR fixes that

### CODE REVIEW

**Comment by gsherwood** [comment]
I have `display_errors` set to `Off` in my default configuration and parse errors are still shown with the `-l` flag. So I can't replicate a setup where this is required.

The whole point of the `-l` flag is for PHP to lint the file, so it would be strange for it to not produce linting errors no matter what your php.ini says. Are you sure this change actually fixed your problem? Have you tried echoing out the `$cmd` var and running the command manually?

**Comment by raul338** [comment]
Sure, here is the output:
```
raul ~/test/PHP_CodeSniffer [display_errors] $ /usr/bin/php -l -d error_prepend_string='' '/home/raul/test/PHP_CodeSniffer/src/Standards/Generic/Tests/PHP/SyntaxUnitTest.inc' 2>&1
Errors parsing /home/raul/test/PHP_CodeSniffer/src/Standards/Generic/Tests/PHP/SyntaxUnitTest.inc
raul ~/test/PHP_CodeSniffer [display_errors] $ php -i | grep error
display_errors => Off => Off
display_startup_errors => Off => Off
error_append_string => no value => no value
error_log => no value => no value
error_prepend_string => no value => no value
error_reporting => 22527 => 22527
html_errors => Off => Off
ignore_repeated_errors => Off => Off
log_errors => Off => Off
log_errors_max_len => 1024 => 1024
track_errors => Off => Off
xmlrpc_error_number => 0 => 0
xmlrpc_errors => Off => Off
intl.error_level => 0 => 0
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.show_error_trace => Off => Off
```

**Comment by gsherwood** [comment]
Thanks for that output. I don't know why my PHP install is always showing errors, but if yours is hiding them then I'm sure others must be too.

**Comment by gsherwood** [comment]
Thanks for this PR.

**Pull request merged**
