### PR TITLE
PHP 8.2 | PSR1/SideEffects: allow for readonly classes

### LINKED ISSUE #3727: Does not work with readonly classes introduced in PHP 8.2
May be closed by ~#3686~ #3728 

**Describe the bug**
In PHP 8.2, "readonly class" feature was introduced.
Using readonly classes, we can shorten readonly property declarations as follows:

```php
class Foo {
    public function __construct(
        private readonly string $foo,
        private readonly int $bar,
    ) {
    }
}
```

equals to:

```php
readonly class Foo {
    public function __construct(
        private string $foo,
        private string $bar,
    ) {
    }
}
```

However, the latest version of phpcs v3.7.1 does not work on the classes which are marked as "readonly". (The phpcs error output is in "To reproduce" section)

**Code sample**
```php
readonly class Foo {
    public function __construct(
        private string $foo,
        private string $bar,
    ) {
    }
}
```

**Custom ruleset**
N/A

**To reproduce**
1. Run phpcs with the default ruleset, with the code sample above.
```
FILE: /project/Foo.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 13
   |         | and the first side effect is on line 13.
   |         | (PSR1.Files.SideEffects.FoundWithSymbols)
----------------------------------------------------------------------
```

**Expected behavior**

**Versions (please complete the following information):**
 - OS: macOS Ventura 13.0.1 (Apple M1 Max; aarch64-apple-darwin)
 - PHP: 8.2.0
 - PHPCS: 3.7.1
 - Standard: PSR12

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jrfnl**
Includes unit test.

Ref:
* https://wiki.php.net/rfc/readonly_classes

Fixes #3727

### CODE REVIEW

**Comment by michnovka** [comment]
Any update regarding this?

**Comment by bladl** [comment]
Any update regarding this?

**Comment by eerison** [comment]
what is missing here?

**Comment by HSken** [comment]
> 
I suspect this is waiting to have all test's successful, this one is still failing
https://github.com/squizlabs/PHP_CodeSniffer/actions/runs/3664153242/jobs/6194396619

**Comment by jrfnl** [comment]
> > what is missing here?
> 
> I suspect this is waiting to have all test's successful, this one is still failing https://github.com/squizlabs/PHP_CodeSniffer/actions/runs/3664153242/jobs/6194396619

No, it's not. PR #3686 has been open for longer than this PR to address that particular issue, which you could have known if you'd read the original issue: https://github.com/squizlabs/PHP_CodeSniffer/issues/3727#issuecomment-1345252998.

What it's waiting for is maintainer time.

**Comment by aykutersoyrmn** [comment]
It'd be amazing to start using `readonly` classes in our projects. I hope the maintainer will find some time to merge and release this PR 🤞

**Comment by michal-swietochowski-tg** [comment]
Waiting for this too. Is there anything blocking this small change?

**Comment by kyryl-bogach** [comment]
@gsherwood 🙏🏻

**Comment by janedbal** [comment]
@gsherwood Hi, did you consider adding few more people as maintainers to this project so that it does not block ton of companies to adapt new PHP features? 

I can confirm that **every year** I actually need to wait months for this project to onboard new PHP syntax to be able to use it in our projects.

-----

I understand that open-source is hard and takes ton of time, but I believe the community will help you with that on such core features. 

Thank you for considering this.

**Comment by kyryl-bogach** [comment]
I'm down to help! :+1

**Comment by helyakin** [comment]
I'm totally down to help as well.

@janedbal is right, I actually have a [PR](https://github.com/nunomaduro/phpinsights/pull/645) on phpinsights wich will also needs this improvement on php code sniffer to be merged.

I'd be happy to contribute in any way, so this kind of mandatory tool for every project keeps on living.

**Comment by jrfnl** [comment]
After seeing all the offers for help here, I've spend a little time creating a [more extensive contributor guide](https://github.com/squizlabs/PHP_CodeSniffer/pull/3830). I look forward to seeing your contributions! 

As for this PR, after the [announcement](https://github.com/squizlabs/PHP_CodeSniffer/issues/3814) a couple of weeks ago, I spend some time creating a PR priority list, which we are currently working our way through. This PR is first on the list for our next maintainers call session in two weeks time (and no, I will not merge my own PRs).

**Comment by asanikovich** [comment]
When will be release of [3.8.0](https://github.com/squizlabs/PHP_CodeSniffer/milestone/31) ?

**Comment by talkinnl** [comment]
In addition to the extra maintainers / or release date discussion:

Maybe the current 3.8.0 scope is too big? It currently contains 46 closed, 25 open tickets.

If some/most open tickets could be postponed to a later version, it would enable getting all the nice done work published. :)

**Comment by delolmo** [comment]
For the time being, anyone encountering this problem can bypass this error by using this phpcs comment before the class declaration:

```php
// phpcs:disable PSR1.Files.SideEffects
final readonly class WhateverClassName
```

This way CI/CD tests won't fail and you can revert the file to the original state once version `3.8` is released.

**Comment by jrfnl** [comment]
FYI: this fix is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).

**Comment by eerison** [comment]
@jrfnl  is it possible to mark this repo as abandoned and archive? Maybe add something in composer to inform

**Comment by fredden** [comment]
@eerison please see #3932 and #3933.

**Comment by jrfnl** [comment]
@eerison As @fredden pointed out, a PR to add a note at the top of the readme is open.

Archiving the repo will possibly be done in six/twelve months time or so, as once the repo is archived you cannot comment on issues/PRs anymore, which is very limiting. For example, I wouldn't have been able to post my previous message informing you of the fix being in the 3.8.0 release, so archiving the repo now would likely hinder instead of help the information about the repo move spreading.

**Comment by asanikovich** [comment]
@jrfnl 
Maybe you should update Readme.md with the latest updates about The Future of PHP_CodeSniffer?

**Comment by fredden** [comment]
@asanikovich please see https://github.com/squizlabs/PHP_CodeSniffer/pull/3933.

**Pull request merged**
