### PR TITLE
Create WebCompat.php report file

### PR DESCRIPTION
**Pull request by dingo-d**
This report will return Full report but suitable for web based output (e.g. in plugins or web apps).

### CODE REVIEW

**Comment by gsherwood** [comment]
Thanks for the submission, but I don't think this report belongs in PHPCS. It's not in a format that I believe will be useful to a wide range of people given it's just the full report with htmlspecialchars.

If you need this report for a project, you can specify the path to the report like this: `phpcs --report=/path/to/WebCompat.php /path/to/code`

**Comment by dingo-d** [comment]
Well I commented in the code, that it could be useful for any plugins - WordPress is currently working with phpcs for checking the coding standards in the themes, and the plan is to have a plugin that will check the theme from within WordPress. Also one could build web apps for checking code standards online as well. Thought that it could be useful to cover that part.

**Comment by jrfnl** [comment]
@dingo-d You can just as easily use the existing checkstyle or xml report formats for that and combine those with an XSL stylesheet.

**Comment by dingo-d** [comment]
I'll have that in mind if I'll do something like that in the future :)

**Pull request closed without merging**
