### PR TITLE
remove (from publishing) files that are not needed for end user

### PR DESCRIPTION
**Pull request by vladyslavstartsev**

### CODE REVIEW

**Comment by jrfnl** [comment]
Loosely related to to #548 and #1908

**Comment by vladyslavstartsev** [comment]
I can remove `tests` folder from this file if you want @jrnl

**Comment by jrfnl** [comment]
@vladyslavstartsev Not up to me. I just thought I'd make you aware of previous discussions which touch on this PR.

**Comment by vladyslavstartsev** [comment]
@jrfnl Done

**Comment by gsherwood** [comment]
Thanks. This has been merged in now. Also gave me a good prompt to clean up the 4.0 branch as well.

**Pull request merged**
