### PR TITLE
Print progress to stderr

### PR DESCRIPTION
**Pull request by exussum12**
When redirecting output to save it, The progress info is also sent.

Progress info should be send to stderr so it can either be redirected
seperatly or just left ot print the progress.

### CODE REVIEW

**Comment by jrfnl** [comment]
Why ?

**Comment by exussum12** [comment]
For when you are directing the real report to save to a file. Progress output is mixed in with this and not what is expected. Calling without redirection this pr makes 0 difference as both streams are shown

**Comment by jrfnl** [comment]
Interesting. I would expect one to use the `--report-full=./myfilename.txt` command line option to save the real report to file instead of redirecting it. Would this PR have any influence of that (and similar) cl options ?

**Comment by exussum12** [comment]
It would be identical to using the report-full option, With much less syntax.

this pr would not change existing behavior , unless someone is parsing out the progress from the standard output,

**Comment by gsherwood** [comment]
This is not a change I want to make right now. There are already options to send different reports to different files, so anyone already capturing STDOUT clearly wants all the debug output they are asking for. Plus, it is a BC break.

I may consider something like this for a major version, but I'd expect all non-report output (including verbose output, debug output, memory/time usage output) to be sent to STDERR as well.

**Comment by gsherwood** [comment]
I'm not going to accept this PR so I'll close it, but I'd be happy to discuss this change on a new issue if you'd like to create one.

**Pull request closed without merging**
