### PR TITLE
Allow "file" in "rule" - phpcs.xsd hotfix

### PR DESCRIPTION
**Pull request by webimpress**
It should be possible to define rule just for some files, so:
```xml
<rule ref="Sniff">
    <exclude-pattern>*</exclude-pattern>
    <file>FILE_TO_CHECK</file>
</rule>
```

### CODE REVIEW

**Comment by webimpress** [comment]
@gsherwood Yes, I know I can use `include-pattern` but it also works with `file`, but it's not allowed by xsd schema.

Is it going to stop working on some point then? If no, I think the schema should be updated, as I did in that PR.

**Comment by gsherwood** [comment]
> Yes, I know I can use include-pattern but it also works with file

It shouldn't work the same as using `file`, and it doesn't when I test it. Those `file` tags are ignored when inside `rule` tags. I can't find any code that would even attempt to process them.

Are you sure your file tags are being processed?

**Comment by webimpress** [comment]
> Are you sure your file tags are being processed?

I've tested it again and you are right - these are __not__ processed. Obviously I did something wrong before... Sorry. Thanks for your help!

**Comment by gsherwood** [comment]
No problem. Thanks for re-testing.

**Pull request closed without merging**
