### PR TITLE
http to https for hyperlink

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Review by fredden — APPROVED** [review]

**Review by jrfnl — APPROVED** [review]
✅ 

I wonder if the codebase should get a complete review of all referenced URLs for `http` vs `https` (and outdated/broken links), but that's outside the scope of this PR.

**Comment by jrfnl** [comment]
> I wonder if the codebase should get a complete review of all referenced URLs for `http` vs `https` (and outdated/broken links), but that's outside the scope of this PR.

I've done this review now and found three more URLs which should be updated. I will submit a separate PR for those.

**Comment by jrfnl** [comment]
Thanks @vanillajonathan !

**Comment by jrfnl** [comment]
FYI: this fix is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).

**Pull request merged**
