### PR TITLE
Array return type hint is sometimes detected as T_ARRAY_HINT instead of T_RETURN_TYPE

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by aik099** [comment]
Can you please also update tests to cover this behavior?

**Comment by gsherwood** [comment]
I can't replicate the error this is trying to fix. While this change wont break anything, I would like to add a unit test to expose the problem. Can you provide some sample code to expose the issue please.

**Comment by kukulich** [comment]
@gsherwood I've just prepared best fix. Here is the code to reproduce the error:

```php
<?php

function foo() : array
{
	$foo;
}

```

**Comment by gsherwood** [comment]
> Here is the code to reproduce the error

Thanks. I thought I tried that already, but I must have stuff up the syntax or something. Easy to replicate it with that code.

**Comment by gsherwood** [comment]
Your first fix was much simpler, and it worked fine. Why did you change it?

**Comment by kukulich** [comment]
@gsherwood The previous fix was fixing only the symptoms, now I've tried to fix the place where the bug really begin. However if you are ok with the simpler fix, I can change the pull request again :)

**Comment by gsherwood** [comment]
> However if you are ok with the simpler fix, I can change the pull request again :)

Yep, I'm ok with the simple fix. It just keeps the return type detection logic in the one place.

I know what you were trying to do with the second patch (I do the same thing sometimes) but I think you were right the first time on this one.

**Comment by kukulich** [comment]
Ok, changed again :)

**Comment by gsherwood** [comment]
Thanks for changing it back, and thanks for the fix.

**Pull request merged**
