### PR TITLE
Fix for #2974

### PR DESCRIPTION
**Pull request by danhunsaker**
This commit brings the code in line with the documentation.

### CODE REVIEW

**Comment by jrfnl** [comment]
@danhunsaker This is not the intention of that particular sniff and this change would be a huge BC-break.

If you want a sniff which indents the `break` to the same level as the `case`/`default` body, use the `PSR2.ControlStructures.SwitchDeclaration` sniff instead.

**Comment by danhunsaker** [comment]
I strongly recommend fixing the documentation, then, because it states otherwise.

**Comment by gsherwood** [comment]
> I strongly recommend fixing the documentation, then, because it states otherwise.

Which documentation do you mean?

**Comment by danhunsaker** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#squizcontrolstructuresswitchdeclaration

**Comment by gsherwood** [comment]
@danhunsaker Thanks for pointing that out. I have corrected the description over there to reflect what the sniff actually enforces.

**Pull request closed without merging**
