### PR TITLE
PHPDocs fixes

### PR DESCRIPTION
**Pull request by michalbundyra**
- [x] ~~removed return statements in constructors~~ (it was merged somewhere before, not from my PR...)
- [x] removed `@return void` tag from constructors docs
- [x] fixed variable types in docs (use imported class instead of invalid FQCN)
- [x] added missing throws tags
- [x] removed redundant throw tag

### CODE REVIEW

**Comment by webimpress** [comment]
@gsherwood Rebased, conflicts resolved. Any chance to include it in 3.3.0 release? Thanks!

**Comment by gsherwood** [comment]
> Any chance to include it in 3.3.0 release?

I wont have a chance to review this for 3.3.0. But I don't really think is matters what version it does into given it shouldn't affect functionality. To be honest, it's going to be fairly low priority given my massive todo list.

**Comment by webimpress** [comment]
@gsherwood Rebased again, can you have a look on it, please? Thanks!

**Comment by jrfnl** [comment]
@webimpress Want some feedback ?

**Comment by webimpress** [comment]
@jrfnl Yes, sure

**Comment by webimpress** [comment]
@jrfnl anything new with this PR? Will you be able to have a look? Thanks!

**Comment by michalbundyra** [comment]
Closing as very old, no interest from maintainers side and conflicted with other changes.

**Pull request closed without merging**
