### PR TITLE
Specify multiple inline exceptions in FunctionCommentThrowTagSniff

### LINKED ISSUE #2728: FunctionCommentThrowTagSniff should allow multiple exceptions for the same throws tag
I think this should be valid
```
/**
 * @throws PHP_Exception1|PHP_Exception2
 */
public function allOK()
{
    throw new PHP_Exception1('Error');
    throw new PHP_Exception2('Error');
}
```
Or an option could exist to allow having multiple exception on one throws tag.

### PR DESCRIPTION
**Pull request by Morerice**
This pull request closes #2728

### CODE REVIEW

**Comment by Morerice** [comment]
The build failure is addressed in PR #2793

**Comment by gsherwood** [comment]
I don't think this sniff should allow this syntax. The intention of this Squiz sniff is to ensure each exception is individually documented. Merging multiple exceptions doesn't allow for this type of documentation, and goes against the phpDoc recommendation as well: https://docs.phpdoc.org/references/phpdoc/tags/throws.html

Happy to hear other opinions.

**Comment by jrfnl** [comment]
I concur with @gsherwood. Using union types also goes against the recommendation in the (draft) PSR 19:

> It is also RECOMMENDED that this tag occurs for every occurrence of an exception, even if it has the same type. By documenting every occurrence a detailed view is created and the consumer knows for which errors to check.

Source: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#514-throws

**Comment by Morerice** [comment]
I understand the problem. Should both the issue and the pr be closed?

**Comment by gsherwood** [comment]
> Should both the issue and the pr be closed?

Good idea.

**Comment by VincentLanglet** [comment]
Using union types for the `@throws` tag also goes against the recommendation in the (draft) PSR 19:

> > It is also RECOMMENDED that this tag occurs for every occurrence of an exception, even if it has the same type. By documenting every occurrence a detailed view is created and the consumer knows for which errors to check.
> 
> Source: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#514-throws

I wasn't aware about this recommendation.

Does a sniff checking that a `@throws` type does not use union types would be accepted ?

**Pull request closed without merging**
