### PR TITLE
Added PSR-12 documentation xml files

### PR DESCRIPTION
**Pull request by tobias-trozowski**
added missing psr12 documentation xml files with code comparisons

### CODE REVIEW

**Comment by jrfnl** [comment]
@tobias-trozowski Could you please check the code samples in your PR for line length ? See the screenshots in #2840 to see what I mean.

**Comment by tobias-trozowski** [comment]
thanks @jrfnl 
I really wasn't aware about that one. i'll have a look next week.

**Comment by jrfnl** [comment]
@tobias-trozowski In case you hadn't found this yet, you can see hat the docs look like on CLI using `--generator=text`.

**Comment by tobias-trozowski** [comment]
screwed this up somehow. created new PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2870

**Pull request closed without merging**
