### PR TITLE
Squiz/ArrayBrackets: Add `fixed` file

### PR DESCRIPTION
**Pull request by jrfnl**
The fixed file highlights that the fixer does not only remove spaces, but also removes comments.

Whether this is intentional or not, is unclear to me.

If it is unintentional, I'd be happy to add a second commit to fix this.

### CODE REVIEW

**Comment by gsherwood** [comment]
The problem with comments is that there really isn't a good place for them to go. If you have any ideas, I'm happy to talk about it. But I'll merge this in as-is to ensure the current behaviour is documented. Thanks.

**Comment by jrfnl** [comment]
> The problem with comments is that there really isn't a good place for them to go. If you have any ideas, I'm happy to talk about it. 

@gsherwood  Removing comments, to me, makes this a risky fixer to run as those comments are normally there for a reason.

I'd suggest leaving comments alone and just making sure there is no whitespace between the bracket and the comment.

If that sounds good to you, I'll open a separate PR to fix the sniff.

**Comment by gsherwood** [comment]
> I'd suggest leaving comments alone and just making sure there is no whitespace between the bracket and the comment.
> 
> If that sounds good to you, I'll open a separate PR to fix the sniff.

Sounds like a good plan.

**Comment by jrfnl** [comment]
@gsherwood I've opened PR #1694 which should sort this out.

**Pull request merged**
