### PR TITLE
Add a `brew install` method

### PR DESCRIPTION
**Pull request by sarahmonster**
This one was easier than the previously listed "easiest way to get started" :smile:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by aik099** [comment]
Are you sure, that this installation way still works? I can't seem to find Homebrew formula for that on https://github.com/Homebrew/homebrew/blob/master/Library/Formula/php-code-sniffer.rb url.

**Comment by aik099** [comment]
The `brew search sniffer` returns following formulas and non of them seems to be official:

* josegonzalez/php/drupal-code-sniffer
* josegonzalez/php/php-code-sniffer
* homebrew/php/drupal-code-sniffer
* homebrew/php/php-code-sniffer
* Caskroom/cask/logicsniffer

**Comment by gsherwood** [comment]
It's nice to know that there is a brew formula for PHPCS out there, but I only want the PHPCS docs to list install methods that I personally support. Then, if something is out of date or not working, they can talk to the people who maintain that project rather than asking here and not getting any real help.

**Pull request closed without merging**
