### PR TITLE
fix #348 add option to treat newline as whitspace

### LINKED ISSUE #348: The "Squiz.WhiteSpace.OperatorSpacing" and new lines issue
When code around mathematical operation or any other operator is split across several lines then new line symbol or any other whitespace (except comment) should be considered as valid whitespace.

```php
$original_amount = $order->GetDBField('SubTotal') + $order->GetDBField('ShippingCost') +
			$order->GetDBField('VAT') + $order->GetDBField('ProcessingFee') + $order->GetDBField('InsuranceFee') -
			$order->GetDBField('GiftCertificateDiscount');
```

Currently one space specifically is asserted to be present.

### PR DESCRIPTION
**Pull request by euoia**
Fixes #348 by adding an option to treat newlines as whitespace.

### CODE REVIEW

**Comment by gsherwood** [comment]
I can't merge this as-is because it is not recording metrics correctly with this change. A few of those IF statements need restructuring as well. I'll make the necessary corrections when I get to request #348.

**Comment by euoia** [comment]
Thanks for looking at this. I have fixed the style errors reported by phpcs in Travis CI. I'm not sure what changes are required to record the metrics correctly, but I'm happy to make them.

**Comment by gsherwood** [comment]
Sorry, I should have explained the metrics stuff. Those metrics lines are now being recorded conditionally, but they need to always be recorded as they describe the code rather than enforce specific standards.

**Comment by euoia** [comment]
I made the change to always record the metrics. It seems to me though that perhaps the metrics *ought* to be recorded conditionally, since the condition in question changes what is considered to be a "space" (and the metric itself refers to a space).

**Comment by aik099** [comment]
Doesn't look right. I think that we need to record actual used char (space or newline) as metric value. Currently it seems to write "space" all the time.

**Comment by euoia** [comment]
I'm happy to make this change but I can't figure out how to get phpcs to report the metrics. Could you tell me how you're testing this? Thanks.

**Comment by euoia** [comment]
Sorry I didn't mean click "close and comment".

**Comment by aik099** [comment]
> but I can't figure out how to get phpcs to report the metrics. Could you tell me how you're testing this? Thanks.

There is special new report type `info` in PHPCS, that does that. See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting

**Comment by euoia** [comment]
Ah got it, thanks. That report type doesn't show up in the help:
```
$ php scripts/phpcs --help
...
        <report>      Print either the "full", "xml", "checkstyle", "csv"
                      "json", "emacs", "source", "summary", "diff"
                      "svnblame", "gitblame", "hgblame" or "notifysend" report
                      (the "full" report is printed by default)
```

**Comment by aik099** [comment]
> That report type doesn't show up in the help:

I think you should report that as a separate issue.

**Comment by euoia** [comment]
> I think you should report that as a separate issue.
For sure, I'll do that.

I have made the improvements you suggested to recording the metrics. I've also made the message "Expected 1 space" say "Expected 1 space or newline" when $treatNewlineAsWhitespace is true.

**Comment by euoia** [comment]
Well that wasn't good. I have tried to fix that error up. I'm having trouble running the tests locally.

**Comment by aik099** [comment]
Error cause of the build: https://travis-ci.org/squizlabs/PHP_CodeSniffer/jobs/46759299#L138

Looks like `$data` parameter isn't passed to `->addError/->addWaring/->addFixableError/->addFixableWarning`, but `%s` is used in error message text.

**Comment by euoia** [comment]
I fixed the error - it occurred because when you add a $data argument to add
FixableError the $error is passed through sprintf. In some of the tests the '%' operator is used and is treated as a format character when passed to sprintf.

**Comment by gsherwood** [comment]
It looks like this metric stuff is confusing you. Metrics are the complete opposite of error messages. They are also incredibly important as I use them to generate my coding standard report data here: http://squizlabs.github.io/PHP_CodeSniffer/analysis/

So I'll look into this myself to ensure the data is being generated correctly and then regenerated for all the repos I collect data about, if needed.

**Comment by euoia** [comment]
See my most recent commit. I'm now matching the behaviour on master where newlines result in a call to recordMetric with a third argument of "newline" instead of the number of spaces.

I also fixed a bug I introducted where a "space after operator" was being reported as a "space before operator".

Maybe there's something else I'm missing...

http://squizlabs.github.io/PHP_CodeSniffer/analysis/ is very nice!

**Comment by gsherwood** [comment]
Thanks for all the effort on this PR, but it was getting more complicated than I thought the change needed to be. I especially didn't want the sniff to suggest that a newline was acceptable, and I can't have the metrics changed in the way you did them because of the way the info report works.

My commit is here: https://github.com/squizlabs/PHP_CodeSniffer/commit/bfbdc6a14bc643ab3d2d95e5d7228be8872f0e37

**Pull request closed without merging**
