### PR TITLE
Added PSR-2 documentation XML files

### PR DESCRIPTION
**Pull request by blue32a**
Thank you for providing a great tool.

## Description

I was looking into sniffs to create a coding standard for my project and it took me a long time to get to the `generator`.
I found some missing in the documentation and am submitting this PR.
Hope that helps.

### Suggested changelog entry

- Added missing `PSR-2` documentation XML files.

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
- [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.
- [x] [Required for new files] I have added any new files to the `package.xml` file.

### CODE REVIEW

**Review by jrfnl — CHANGES_REQUESTED** [review]
@blue32a Thank you for your willingness to contribute.

I have reviewed these XML docs, checked for common mistakes and tested them in CLI.

Findings:
* `PSR2.Files.ClosingTag`: ✅ 
* `PSR2.Methods.FunctionClosingBrace`: I'd recommend some minor tweaks to the code sample descriptions to make it more obvious what the sniff is looking for.
* `PSR2.Methods.FunctionCallSignature`:
    - The code samples used aren't function calls, while the sniff is about function calls.
    - I'd recommend some tweaks to the code sample descriptions to make it more obvious what the sniff is looking for.
    - There are numerous additional checks the sniff does, but which are not mentioned in the docs.
        This is not a blocker, as those can be added at a later time, but it should be noted all the same.
        Extra checks currently not mentioned:
        - First argument in a multi-line function call must be on a new line.
        - Only one argument per line in a multi-line function call.
        - No blank lines in a multi-line function call.

**Comment by jrfnl** [comment]
P.S.: The new files should also be added to the `package.xml` file.

**Comment by blue32a** [comment]
@jrfnl Thank you for your review.

I have updated the PR with your findings.

**Review by jrfnl — APPROVED** [review]
> I had missed it. Three new documents have been added to `package.xml`.

@blue32a Thank you! All looks good to me now ✅

**Comment by jrfnl** [comment]
FYI: this fix is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).

**Pull request merged**
