### PR TITLE
Squiz/FileComment: add fixed file

### PR DESCRIPTION
**Pull request by jrfnl**
[Missing fixed files series PR]

The sniff contains fixers, but didn't have `fixed` files.

While I was at it, I've done a cursory review of the sniff and have added some additional unit test files for those errors which were, so far, untested.

### CODE REVIEW

**Comment by gsherwood** [comment]
The fixer uses the current year to generate the copyright statement, which has since broken these tests now that we are in 2019. I'll update them to use 2019 so at least the fixers are tested for 12 months, but a better solution would be nice. I can't think of one off the top of my head though.

**Comment by gsherwood** [comment]
Thanks for the test files

**Comment by gsherwood** [comment]
@jrfnl Yeah, option 2 is probably the way to go there. Ultimately, this sniff needs to be removed. It's a long forgotten sniff from the early days of PHPCS and it should be gone. So maybe it's not worth making this change at all.

**Comment by jrfnl** [comment]
@gsherwood Well, in that case, maybe we should leave it until the `AbstractDocblockSniff` is in place (#2222) ?
Once that abstract is available it will be so much easier for external standards to create their own `FileComment` sniff that removing this sniff should give less friction.

**Comment by gsherwood** [comment]
> Well, in that case, maybe we should leave it until the `AbstractDocblockSniff` is in place

Done

**Pull request merged**
