### PR TITLE
Fix invalid namespace in phpdoc (\PHP_CodeSniffer\Files\File)

### PR DESCRIPTION
**Pull request by mzk**
The invalid phpdoc namespace fixed.

### Related issues/external references

Fixes #

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change. (https://github.com/squizlabs/PHP_CodeSniffer/pull/3256 similar)
- [ ] I have read the [Contribution Guidelines](.github/CONTRIBUTING.md).
- [ ] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.
- [ ] [Required for new files] I have added any new files to the `package.xml` file.

### CODE REVIEW

**Review by jrfnl — CHANGES_REQUESTED** [review]
@mzk Thanks for this PR. The alignment of the parameters in the docblocks will need to be fixed though before this can be merged.

**Comment by mzk** [comment]
@jrfnl  Done, thx.

**Review by jrfnl — APPROVED** [review]
Thanks for fixing that up! Merging now.

**Comment by jrfnl** [comment]
FYI: this fix is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).

**Pull request merged**
