### PR TITLE
Svn-pre-commit hook: use env in shebang

### PR DESCRIPTION
**Pull request by sserbin**
Same way as scripts/phpcs and scripts/phpcbf do.

### CODE REVIEW

**Comment by aik099** [comment]
You're suggesting that this hook doesn't work by default due invalid shebang?

**Comment by sserbin** [comment]
That's right. Kind of makes it unsable when installed through composer. 
This is also in line with e0beeefdf90c4b8c693af8bc7000e15cf0c24ca6

**Comment by aik099** [comment]
Ah, I see now. The `@php_bin@` was probably replaced with actual PHP path only during PEAR install.

**Comment by gsherwood** [comment]
I'll merge this in and fix the package.xml (this change makes the script unusable with PEAR) but be aware that this script has been removed from the 3.0 version.

**Comment by gsherwood** [comment]
Thanks for the PR.

**Pull request merged**
