### PR TITLE
Improves Squiz\Sniffs\Commenting\FunctionCommentThrowTagSniff

### PR DESCRIPTION
**Pull request by flobee**
+ Adds property to switch between error and warning output. (We need it
  for CI purpose, Option for third party usage)
+ Adds ignoreing netbeans (editor) configs
+ Improves CONTRIBUTING.md to not stay alone on first run ;-)

Happy sniffing :-)

btw: sniffs and unit tests where tested on: 7.3.11-1+0~20191026.48+debian10~1.gbpf71ca0

### CODE REVIEW

**Comment by jrfnl** [comment]
>     * Adds property to switch between error and warning output. (We need it
>       for CI purpose, Option for third party usage)

You can already do this by using a custom `phpcs.xml.dist` file in your project and using the below snippet:
```xml
 <rule ref="Squiz.Commenting.FunctionCommentThrowTag">
  <type>warning</type>
 </rule>
``` 

>     * Adds ignoreing netbeans (editor) configs

That is a developer specific setting and should not go into the project `.gitignore` file, but in your personal `.git/info/exclude` file.


Suggest: close.

**Comment by flobee** [comment]
Hi

> > * Adds ignoreing netbeans (editor) configs

> That is a developer specific setting and should not go into the project `.gitignore` file, but in your personal `.git/info/exclude` file.
> 
Like '.idea/*'? no different!

**Comment by jrfnl** [comment]
> Like '.idea/*'? no different!

I agree, that shouldn't be in a `gitignore` either.

**Comment by flobee** [comment]
> > Like '.idea/*'? no different!
> 
> I agree, that shouldn't be in a `gitignore` either.

On each machine? What do you think what this file should include and why?

**Comment by flobee** [comment]
I revert my branch with the changes of "FunctionCommentThrowTagSniff'. So just the littel changes can be pulled. Thxs for the hints.

**Comment by gsherwood** [comment]
I'm going to close this as I don't think either of these changes are required. If anyone has strong opinions, please feel free to post them.

**Pull request closed without merging**
