### PR TITLE
Update repos.json

### PR DESCRIPTION
**Pull request by mverma16**
Added faveo-helpdesk an open source repository to analyse it for code conventions. Please check it and make changes wherever required. Thanks in advance.

### CODE REVIEW

**Comment by gsherwood** [comment]
Here is the report for this new repo: http://squizlabs.github.io/PHP_CodeSniffer/analysis/ladybirdweb/faveo-helpdesk/index.html

**Comment by mverma16** [comment]
Hello there, thanks for the detailed report about code analysis for our repository. It seems like we are lacking somewhere in following coding standards in our project as we've got C- consistency. We have decided to rectified our errors but could not figure out how to do it. Now we are trying to follow PSR coding standard as much as possible. Also we are using Code_sniffer to check our code for errors in coding standard and fixing it by PHP-CS-Fixer. My doubt is we are using Laravel 5.0 framework in our project and Laravel 5.0 does not follow PSR2 for coding style. So can you tell me what standard does this code analysis test. Also how frequently do you test the repositories and generate reports? As our we've debugged our code at certain level and our boss wants to see the report. Is there any automatic way to generate the report so that we can track our progress.
Thank you

**Comment by gsherwood** [comment]
> We have decided to rectified our errors but could not figure out how to do it. Now we are trying to follow PSR coding standard as much as possible.

This report doesn't actually look at what coding standard you are using. It just tries to see how consistent your code is. If you look at the report, the metrics are ordered by least consistent to most consistent. So the biggest thing to probably work on is your line indent style (pick tabs or spaces, but not both), consistency of your filenames, and spacing around string concat and arithmetic operators.

> Also we are using Code_sniffer to check our code for errors in coding standard and fixing it by PHP-CS-Fixer.

You can also use PHPCS to fix the errors directly. PHPCS comes with a script called PHPCBF, which accepts the exact same arguments. If you want to check your code against PSR2, you can run `phpcs --standard=PSR2 faveo-helpdesk --ignore=*/vendor/* --extensions=php,inc` and if you want all your code to conform to PSR2, you can run `phpcbf --standard=PSR2 faveo-helpdesk --ignore=*/vendor/* --extensions=php,inc`, which will fix a lot of errors automatically.

I just ran the latest PHPCS code over your repo and got this summary for PSR2:
```
A TOTAL OF 5242 ERRORS AND 2069 WARNINGS WERE FOUND IN 658 FILES
PHPCBF CAN FIX 4678 OF THESE SNIFF VIOLATIONS AUTOMATICALLY
```
So PHPCBF could automatically fix 90% of your PSR2 errors.

> My doubt is we are using Laravel 5.0 framework in our project and Laravel 5.0 does not follow PSR2 for coding style.

The report doesn't checkout your composer dependencies, and I have excluded your vendor folder as well, so the report is just checking your code.

> Also how frequently do you test the repositories and generate reports?

Once a month.

> Is there any automatic way to generate the report so that we can track our progress.

You can look at the reports each month, or you can run PHPCS with the `info` report by using this command `phpcs --standard=PSR2 faveo-helpdesk --ignore=*/vendor/* --extensions=php,inc --report=info`

Or, if you want PHPCS to check every possible metric it knows about, you can run this:
`phpcs --standard=Generic,Squiz,PEAR,PSR2 faveo-helpdesk --ignore=*/vendor/* --extensions=php,inc --report=info`

I just ran that command on your report and got this result:
```
PHP CODE SNIFFER INFORMATION REPORT
----------------------------------------------------------------------
Adjacent assignments aligned: yes [2298/3359, 68.41%]
	no => 1061 (31.59%)

Array end comma: yes [53/53, 100%]

Array keyword case: lower [17/17, 100%]

Brackets around echoed strings: no [225/229, 98.25%]
	yes => 4 (1.75%)

CamelCase class name: yes [292/434, 67.28%]
	no => 142 (32.72%)

CamelCase function name: no [10/10, 100%]

CamelCase method name: yes [1114/1297, 85.89%]
	no => 183 (14.11%)

Class defined in namespace: no [218/434, 50.23%]
	yes => 216 (49.77%)

Class has doc comment: yes [221/434, 50.92%]
	no => 213 (49.08%)

Class opening brace placement: new line [432/434, 99.54%]
	same line => 2 (0.46%)

Constant name case: upper [56/56, 100%]

Control structure defined inline: no [2255/2265, 99.56%]
	yes => 10 (0.44%)

Declarations and side effects mixed: no [497/521, 95.39%]
	yes => 24 (4.61%)

EOL char: \n [521/521, 100%]

File extension for class files: .php [399/399, 100%]

File extension for non-class files: .php [122/122, 100%]

File has doc comment: no [437/521, 83.88%]
	yes => 84 (16.12%)

Function has doc comment: yes [918/1369, 67.06%]
	no => 451 (32.94%)

Function opening brace placement: same line [1601/2957, 54.14%]
	new line => 1356 (45.86%)

Inline comment style: // ... [1755/2365, 74.21%]
	/* ... */ => 610 (25.79%)

Line indent: spaces [41096/42696, 96.25%]
	tabs => 1487 (3.48%)
	mixed => 113 (0.26%)

Line length: 80 or less [46630/53081, 87.85%]
	81-120 => 4578 (8.62%)
	121-150 => 1108 (2.09%)
	151 or more => 765 (1.44%)

Lowercase filename: no [319/521, 61.23%]
	yes => 202 (38.77%)

Multiple statements on same line: no [11582/11612, 99.74%]
	yes => 30 (0.26%)

Newline at EOF: yes [462/521, 88.68%]
	no => 59 (11.32%)

Number of newlines at EOF: 1 [437/437, 100%]

One class per file: yes [399/434, 91.94%]
	no => 35 (8.06%)

PHP closing tag at EOF: no [521/521, 100%]

PHP closing tag at end of PHP-only file: no [437/437, 100%]

PHP constant case: lower [999/999, 100%]

PHP keyword case: lower [10641/10641, 100%]

PHP short open tag used: no [988/988, 100%]

Private method prefixed with underscore: no [26/38, 68.42%]
	yes => 12 (31.58%)

Short array syntax used: yes [1009/1026, 98.34%]
	no => 17 (1.66%)

Space after operator: 1 [10041/10183, 98.61%]
	0 => 97 (0.95%)
	newline => 24 (0.24%)
	2 => 21 (0.21%)

Space before operator: 1 [1493/1595, 93.61%]
	0 => 96 (6.02%)
	newline => 6 (0.38%)

Spaces after control structure open parenthesis: 0 [1948/1948, 100%]

Spaces before control structure close parenthesis: 0 [1939/1948, 99.54%]
	1 => 9 (0.46%)

Spacing after cast statement: 1 [21/21, 100%]

Spacing after object operator: 0 [10310/10314, 99.96%]
	newline => 4 (0.04%)

Spacing after string concat: 0 [2004/2120, 94.53%]
	1 => 102 (4.81%)
	2 => 10 (0.47%)
	newline => 4 (0.19%)

Spacing before object operator: 0 [10057/10314, 97.51%]
	newline => 257 (2.49%)

Spacing before string concat: 0 [2000/2120, 94.34%]
	1 => 97 (4.58%)
	newline => 13 (0.61%)
	2 => 10 (0.47%)

Use of ELSE IF or ELSEIF: elseif [83/83, 100%]

Using byte order mark: no [216/216, 100%]

----------------------------------------------------------------------
Time: 32.39 secs; Memory: 42Mb
```
This report tells me you've obviously been working on your code standards because your indent and operator spacing figures are now close to 100%. You can use this report to find other metrics where the figures are not close to 100% and work on those.

I hope that information helps.

**Comment by gsherwood** [comment]
Just leaving a note that the 1st March data has been published and all your work on improving coding standards is now very obvious: http://squizlabs.github.io/PHP_CodeSniffer/analysis/ladybirdweb/faveo-helpdesk/index.html

Nice work.

**Comment by mverma16** [comment]
Thank you very much. This report is very helpful for us to realize our errors. We are working on it and we hope to refine our code as much as possible.

**Pull request merged**
