### PR TITLE
callable and self tokens should be converted to T_RETURN_TYPE too

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by aik099** [comment]
Please also add tests covering code changes.

**Comment by kukulich** [comment]
@aik099 Unfortunately I didn't find any test where I could add new checks.

**Comment by aik099** [comment]
You can look at commit, where T_RETURN_TYPE token support was added initially. I bet that commit or commits right after that are adding these tests.

**Comment by kukulich** [comment]
@aik099 No, there are not tests for this. There are only tests for ArrayDeclarationSniff: https://github.com/squizlabs/PHP_CodeSniffer/commit/71d0292dbfd17cf68fbfacf08cc9b4c330a79a2c

**Comment by aik099** [comment]
Then you can add your tests to same sniff to be consistent.

**Comment by aik099** [comment]
There are no dedicated tokenizer tests, because it's tested indirectly through sniffs that provide PHP code for tokenizing.

**Comment by kukulich** [comment]
@aik099 "self" and "callable" in ArrayDeclarationSniff really don't make any sense. And as I said earlier I didn't find any suitable sniff tests (for "self" or "callable") where I could add new checks.

**Comment by aik099** [comment]
Doesn't https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Functions/FunctionDeclarationSniff.php sniff look suitable? It checks function declaration.

**Comment by gsherwood** [comment]
Thanks for the PR. I also include T_PARENT as this is valid as well, according to the RFC.

**Pull request merged**
