### PR TITLE
Ignore files when exporting package

### PR DESCRIPTION
**Pull request by simonschaufi**
This commit is part of a campaign to reduce the amount of data transferred to save global bandwidth and reduce the amount of CO2. See https://github.com/Codeception/Codeception/pull/5527 for more info.

### CODE REVIEW

**Comment by simonschaufi** [comment]
What about `CodeSniffer.conf.dist`? Can this file also get excluded?

**Comment by jrfnl** [comment]
Related to #548, #1908, #2991, #3176 - the change for tests will not be accepted in the 3.x branch. The tests will be `export-ignore`d in the 4.x branch.

The update for `.github/` is justified. This is a recently new directory.

**Comment by simonschaufi** [comment]
Ok I see but I really wonder why people depend on third party tests... When can I expect a 4.0 release?

**Comment by gsherwood** [comment]
I've added the `.github` dir to the export ignore list. Thanks for pointing that out.

The test dirs are ignored in the 4.0 branch but I do not have a release date for that version.

**Pull request closed without merging**
