### PR TITLE
Removed commited git confilict

### PR DESCRIPTION
**Pull request by JarJak**

### CODE REVIEW

**Comment by jrfnl** [comment]
Duplicate of #1314, #1584.
Not to discourage you from contributing, but this is a valid test case.

**Comment by JarJak** [comment]
Oh, OK :)

30.08.2017 2:51 PM "Juliette" <notifications@github.com> napisał(a):

**Comment by gmponos** [comment]
Since there are already two other issues I would've suggest to add a comment there in order not to be confusing.

**Comment by gsherwood** [comment]
I added the comment. Thanks.

**Pull request closed without merging**
